src/Back/SchoolBundle/Entity/PathwayPrice.php
<?php

namespace Back\SchoolBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * PathwayPrice
 *
 * @ORM\Table(name="wws_pathway_price")
 * @ORM\Entity
 */
class PathwayPrice
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255,nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="price", type="decimal", precision=11, scale=3)
     */
    private $price;

    /**
     * @var integer
     *
     * @ORM\Column(name="week", type="integer",nullable=true)
     */
    private $week;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startDate", type="date", nullable=true)
     */
    private $startDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="endDate", type="date" , nullable=true)
     */
    private $endDate;

    /**
     * @ORM\ManyToOne(targetEntity="Course", inversedBy="pathwayPrices")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    protected $course;

    /**
     * @ORM\ManyToOne(targetEntity="Room", inversedBy="pathwayPrices")
     * @ORM\JoinColumn(onDelete="CASCADE")
     * 
     */
    protected $room;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return PathwayPrice
     */
    public function setName($name)
    {
        $this->name=$name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set price
     *
     * @param string $price
     * @return PathwayPrice
     */
    public function setPrice($price)
    {
        $this->price=$price;

        return $this;
    }

    /**
     * Get price
     *
     * @return num 
     */
    public function getPrice()
    {
        return number_format($this->price, 2, '.', '');
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     * @return PathwayPrice
     */
    public function setStartDate($startDate)
    {
        $this->startDate=$startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime 
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set endDate
     *
     * @param \DateTime $endDate
     * @return PathwayPrice
     */
    public function setEndDate($endDate)
    {
        $this->endDate=$endDate;

        return $this;
    }

    /**
     * Get endDate
     *
     * @return \DateTime 
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set course
     *
     * @param \Back\SchoolBundle\Entity\Course $course
     * @return PathwayPrice
     */
    public function setCourse(\Back\SchoolBundle\Entity\Course $course=null)
    {
        $this->course=$course;

        return $this;
    }

    /**
     * Get course
     *
     * @return \Back\SchoolBundle\Entity\Course 
     */
    public function getCourse()
    {
        return $this->course;
    }

    /**
     * Set room
     *
     * @param \Back\SchoolBundle\Entity\Room $room
     * @return PathwayPrice
     */
    public function setRoom(\Back\SchoolBundle\Entity\Room $room=null)
    {
        $this->room=$room;

        return $this;
    }

    /**
     * Get room
     *
     * @return \Back\SchoolBundle\Entity\Room 
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * get number of week between two dates
     * 
     * @return integer
     */
    public function getNumbrerWeeks()
    {
        $nbrJours=$dureesejour=(strtotime($this->endDate->format("Y-m-d")) - strtotime($this->startDate->format("Y-m-d")));
        return round($nbrJours / 86400 / 7);
    }


    /**
     * Set week
     *
     * @param integer $week
     * @return PathwayPrice
     */
    public function setWeek($week)
    {
        $this->week = $week;

        return $this;
    }

    /**
     * Get week
     *
     * @return integer 
     */
    public function getWeek()
    {
        return $this->week;
    }
    
    public function __clone()
    {
        if ($this->id)
        {
            $this->id = null ;
        }
    }
}

src/Back/SchoolBundle/Form/AccommodationType.php
<?php

namespace Back\SchoolBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AccommodationType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Back\SchoolBundle\Entity\Accommodation'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'back_schoolbundle_accommodation';
    }
}

src/Back/SchoolBundle/Form/PriceType.php
<?php

namespace Back\SchoolBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PriceType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('weekStart')
                ->add('weekEnd')
                ->add('price')
                ->add('fix', 'checkbox', array(
                    'label'   =>'Price fix',
                    'required'=>false
                ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'=>'Back\SchoolBundle\Entity\Price'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'back_schoolbundle_price';
    }

}

src/Back/SchoolBundle/Controller/AccommodationsController.php
<?php

namespace Back\SchoolBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\ORM\EntityRepository;
use Back\SchoolBundle\Entity\Accommodation;
use Back\SchoolBundle\Form\AccommodationType;
use Back\SchoolBundle\Entity\SchoolLocation;
use Back\SchoolBundle\Entity\Room;
use Back\SchoolBundle\Form\RoomType;
use Back\SchoolBundle\Entity\Price;
use Back\SchoolBundle\Form\PriceType;
use Back\SchoolBundle\Entity\PathwayPrice;
use Back\SchoolBundle\Form\PathwayPriceType;

class AccommodationsController extends Controller
{

    public function listAction(SchoolLocation $schoolLocation)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        $accommodation=new Accommodation();
        $accommodation->setSchoolLocation($schoolLocation);
        $form=$this->createForm(new AccommodationType(), $accommodation);
        $request=$this->getRequest();
        if($request->isMethod("POST"))
        {
            $form->submit($request);
            if($form->isValid())
            {
                $accommodation=$form->getData();
                $em->persist($accommodation);
                $em->flush();
                $session->getFlashBag()->add('success', "Your accommodation has been added successfully");
                return $this->redirect($this->generateUrl("list_accommodations", array( 'id'=>$schoolLocation->getId() )));
            }
        }
        return $this->render("BackSchoolBundle:accommodations:list.html.twig", array(
                    'form'  =>$form->createView(),
                    'school'=>$schoolLocation,
        ));
    }

    public function deleteAccommodationsAction(Accommodation $accommodation)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        try
        {
            $em->remove($accommodation);
            $em->flush();
            $session->getFlashBag()->add('success', " Your accommodation has been successfully removed ");
        }
        catch(\Exception $ex)
        {
            $session->getFlashBag()->add('danger', 'This accommodation is used by another table ');
        }
        return $this->redirect($this->generateUrl("list_accommodations", array( 'id'=>$accommodation->getSchoolLocation()->getId() )));
    }

    public function editAccommodationsAction(SchoolLocation $schoolLocation, Accommodation $accommodation)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        $accommodation->setSchoolLocation($schoolLocation);
        $form=$this->createForm(new AccommodationType(), $accommodation);
        $request=$this->getRequest();
        if($request->isMethod("POST"))
        {
            $form->submit($request);
            if($form->isValid())
            {
                $accommodation=$form->getData();
                $em->persist($accommodation);
                $em->flush();
                $session->getFlashBag()->add('success', "Your accommodation has been added successfully");
                return $this->redirect($this->generateUrl("list_accommodations", array(
                                    'id'           =>$schoolLocation->getId(),
                                    'accommodation'=>$accommodation->getId()
                )));
            }
        }
        return $this->render("BackSchoolBundle:accommodations:edit.html.twig", array(
                    'form'         =>$form->createView(),
                    'school'       =>$schoolLocation,
                    'accommodation'=>$accommodation,
        ));
    }

    public function roomsAction(SchoolLocation $schoolLocation, Accommodation $accommodation, $id2)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        if($id2 == null)
            $room=new Room();
        else
            $room=$em->getRepository("BackSchoolBundle:Room")->find($id2);
        $form=$this->createForm(new RoomType, $room);
        $request=$this->getRequest();
        if($request->isMethod("POST"))
        {
            $form->submit($request);
            if($form->isValid())
            {
                $room=$form->getData();
                $em->persist($room->setAccommodation($accommodation));
                $em->flush();
                $session->getFlashBag()->add('success', "Your room has been added successfully");
                return $this->redirect($this->generateUrl("rooms_accommodations", array(
                                    'id'           =>$schoolLocation->getId(),
                                    'accommodation'=>$accommodation->getId()
                )));
            }
        }
        return $this->render("BackSchoolBundle:accommodations:rooms.html.twig", array(
                    'form'         =>$form->createView(),
                    'school'       =>$schoolLocation,
                    'accommodation'=>$accommodation,
                    'room'         =>$room,
        ));
    }

    public function deleteRoomAction(Room $room)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        try
        {
            $em->remove($room);
            $em->flush();
            $session->getFlashBag()->add('success', " Your room has been successfully removed ");
        }
        catch(\Exception $ex)
        {
            $session->getFlashBag()->add('danger', 'This room is used by another table ');
        }
        return $this->redirect($this->generateUrl("rooms_accommodations", array(
                            'id'           =>$room->getAccommodation()->getSchoolLocation()->getId(),
                            'accommodation'=>$room->getAccommodation()->getId()
        )));
    }

    public function priceAction(SchoolLocation $schoolLocation, Accommodation $accommodation)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        $price=new Price();
        $form=$this
                ->createForm(new PriceType(), $price)
                ->add('room', "entity", array(
            'class'        =>'BackSchoolBundle:Room',
            'query_builder'=>function(EntityRepository $er) use ($accommodation){
                return $er->createQueryBuilder('r')
                        ->where('r.accommodation = :id')
                        ->setParameter('id', $accommodation->getId());
                ;
            }
        ));
        $request=$this->getRequest();
        if($request->isMethod("POST"))
        {
            $form->submit($request);
            if($form->isValid())
            {
                $price=$form->getData();
                if($this->isValidPrice($price))
                {
                    $em->persist($price);
                    $em->flush();
                    $session->getFlashBag()->add('success', "Your price has been added successfully");
                    return $this->redirect($this->generateUrl("price_accommodations", array(
                                        'id'           =>$schoolLocation->getId(),
                                        'accommodation'=>$accommodation->getId()
                    )));
                }
                else
                    $session->getFlashBag()->add('danger', "Please verif your weeks");
            }
        }
        return $this->render("BackSchoolBundle:accommodations:prices.html.twig", array(
                    'form'         =>$form->createView(),
                    'school'       =>$schoolLocation,
                    'accommodation'=>$accommodation,
        ));
    }

    public function deletePriceAction(Price $price)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        try
        {
            $em->remove($price);
            $em->flush();
            $session->getFlashBag()->add('success', " Your room has been successfully removed ");
        }
        catch(\Exception $ex)
        {
            $session->getFlashBag()->add('danger', 'This room is used by another table ');
        }
        return $this->redirect($this->generateUrl("price_accommodations", array(
                            'id'           =>$price->getRoom()->getAccommodation()->getSchoolLocation()->getId(),
                            'accommodation'=>$price->getRoom()->getAccommodation()->getId()
        )));
    }

    public function isValidPrice(Price $price)
    {
        foreach($price->getRoom()->getPrices() as $prix)
        {
            if($price->getWeekEnd() != $prix->getWeekEnd() || $price->getWeekStart() != $prix->getWeekStart() || $price->getPrice() != $prix->getPrice())
            {
                if($price->getWeekStart() >= $prix->getWeekStart() && $price->getWeekStart() <= $prix->getWeekEnd())
                    return false;
                if($price->getWeekEnd() >= $prix->getWeekStart() && $price->getWeekEnd() <= $prix->getWeekEnd())
                    return false;
            }
        }
        return true;
    }

    public function pathwayPriceAction(SchoolLocation $schoolLocation, Accommodation $accommodation)
    {
        $em=$this->getDoctrine()->getManager();
        $session=$this->getRequest()->getSession();
        $price=new PathwayPrice();
        $form=$this
                ->createForm(new PathwayPriceType(), $price)
                ->add('room', "entity", array(
            'class'        =>'BackSchoolBundle:Room',
            'query_builder'=>function(EntityRepository $er) use ($accommodation){
                return $er->createQueryBuilder('r')
                        ->where('r.accommodation = :id')
                        ->setParameter('id', $accommodation->getId());
                ;
            }
        ));
        $request=$this->getRequest();

src/Back/SchoolBundle/Resources/views/accommodations/edit.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}{{ school.name }}{% endblock %}
{% block description %}Accommodations{% endblock %}
{% block body %}
    <div class="tabbable">
        {% include 'BackSchoolBundle:school:menu.html.twig' %}
        {% include 'BackSchoolBundle:accommodations:menu.html.twig' %}
        <div class="tab-content">
            <div class="container-fluid container-fullw bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ path('edit_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}" {{ form_enctype(form) }}  method="post" role="form" id="form">
                            {{ form_widget(form._token) }}
                            <div class="row">
                                {{ formulaire.input("col-md-2","Name",form.name,true) }}
                                {{ formulaire.input("col-md-2","Type",form.typeAccommodation,true) }}
                                {{ formulaire.input("col-md-4","Description",form.description,true) }}
                            </div>
                            {{ macro.enregistrer }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Back/SchoolBundle/Resources/views/accommodations/list.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}{{ school.name }}{% endblock %}
{% block description %}Accommodations{% endblock %}
{% block body %}
    <div class="tabbable">
        {% include 'BackSchoolBundle:school:menu.html.twig' %}
        <div class="tab-content">
            <div class="container-fluid container-fullw bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ path('list_accommodations',{'id':school.id}) }}" {{ form_enctype(form) }}  method="post" role="form" id="form">
                            {{ form_widget(form._token) }}
                            <div class="row">
                                {{ formulaire.input("col-md-2","Name",form.name,true) }}
                                {{ formulaire.select2("col-md-2","Type",form.typeAccommodation,true) }}
                                {{ formulaire.input("col-md-4","Description",form.description,true) }}
                            </div>
                            {{ macro.enregistrer }}
                        </form>
                    </div>
                    <div class="col-md-12">
                        <h5 class="over-title margin-bottom-15">Accommodations <span class="text-bold">list</span></h5>
                        <table class="table table-hover" id="sample-table-1">
                            <thead>
                                <tr>
                                    <th class="center">Name</th>
                                    <th class="center">Type</th>
                                    <th class="center">Description</th>
                                    <th class="center">Rooms</th>
                                    <th class="center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for accommodation in school.accommodations %}
                                    <tr>
                                        <td class="center">{{ accommodation.name }}</td>
                                        <td class="center">{{ accommodation.typeAccommodation }}</td>
                                        <td class="center">{{ accommodation.description }}</td>
                                        <td>
                                            {% for room in accommodation.rooms %}
                                                - {{ room.name }}<br>
                                            {% endfor %}
                                        </td>
                                        <td class="center">
                                            {{ macro.fiche(path('edit_accommodations',{'id':school.id,'accommodation':accommodation.id})) }}
                                            {{ macro.delete(path('delete_accommodations',{'id':accommodation.id})) }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Back/SchoolBundle/Resources/views/accommodations/menu.html.twig
<ul class="nav nav-tabs">
    <li {% if app.request.get('_route')=='edit_accommodations' %}class="active"{% endif %}>
        <a href="{{ path('edit_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}">
            {{ accommodation.name }}
        </a>
    </li>
    <li {% if app.request.get('_route')=='rooms_accommodations' %}class="active"{% endif %}>
        <a href="{{ path('rooms_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}">
            Rooms ({{ accommodation.rooms|length }})
        </a>
    </li>
    {% if school.type==1 %}
        <li {% if app.request.get('_route')=='price_accommodations' %}class="active"{% endif %}>
            <a href="{{ path('price_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}">
                Prices ({{ accommodation.getNumberPrice }})
            </a>
        </li>
    {% else %}
        <li {% if app.request.get('_route')=='pathway_price_accommodations' %}class="active"{% endif %}>
            <a href="{{ path('pathway_price_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}">
                Prices ({{ accommodation.getNumberPathwayPrice }})
            </a>
        </li>
    {% endif %}
</ul>

src/Back/SchoolBundle/Resources/views/accommodations/pathway_prices.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}{{ school.name }}{% endblock %}
{% block description %}Accommodations{% endblock %}
{% block body %}
    <div class="tabbable">
        {% include 'BackSchoolBundle:school:menu.html.twig' %}
        {% include 'BackSchoolBundle:accommodations:menu.html.twig' %}
        <div class="tab-content">
            <div class="container-fluid container-fullw bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ path('pathway_price_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}" {{ form_enctype(form) }}  method="post" role="form" id="form">
                            {{ form_widget(form._token) }}
                            <div class="row">
                                {{ formulaire.select2("col-md-2","Room",form.room,true) }}
                                {{ formulaire.input("col-md-2","Start date",form.startDate,true) }}
                                {{ formulaire.input("col-md-2","End Date",form.endDate,true) }}
                                {{ formulaire.input("col-md-2","Price",form.price,true) }}
                            </div>
                            {{ macro.enregistrer }}
                        </form>
                    </div>
                    <div class="col-md-12">
                        <h5 class="over-title margin-bottom-15">Prices <span class="text-bold">list</span></h5>
                        <table class="table" id="sample-table-1">
                            <thead>
                                <tr>
                                    <th class="center">Room</th>
                                    <th class="center">Start date</th>
                                    <th class="center">End Date</th>
                                    <th class="center">Number of weeks</th>
                                    <th class="center">Price</th>
                                    <th class="center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for room in accommodation.rooms %}
                                    {% for price in room.pathwayPrices %}
                                        <tr>
                                            {% if loop.index == 1 %}
                                                <td class="center" rowspan="{{ room.pathwayPrices|length }}">{{ room }}</td>
                                            {% endif %}
                                            <td class="center">{{ price.startDate|date('d/m/Y') }}</td>
                                            <td class="center">{{ price.endDate|date('d/m/Y') }}</td>
                                            <td class="center">{{ price.numbrerWeeks }}</td>
                                            <td class="center">{{ price.price }}  {{ price.room.accommodation.schoolLocation.currency.code }}</td>
                                            <td class="center">
                                                {{ macro.delete(path('delete_pathway_price',{'id':price.id})) }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Back/SchoolBundle/Resources/views/accommodations/prices.html.twig
{% extends ":Back:base.html.twig" %}
{% block title %}{{ school.name }}{% endblock %}
{% block description %}Accommodations{% endblock %}
{% block body %}
    <div class="tabbable">
        {% include 'BackSchoolBundle:school:menu.html.twig' %}
        {% include 'BackSchoolBundle:accommodations:menu.html.twig' %}
        <div class="tab-content">
            <div class="container-fluid container-fullw bg-white">
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ path('price_accommodations',{'id':school.id,'accommodation':accommodation.id}) }}" {{ form_enctype(form) }}  method="post" role="form" id="form">
                            {{ form_widget(form._token) }}
                            <div class="row">
                                {{ formulaire.select2("col-md-2","Room",form.room,true) }}
                                {{ formulaire.input("col-md-2","Week start",form.weekStart,true) }}
                                {{ formulaire.input("col-md-2","Week end",form.weekEnd,true) }}
                                {{ formulaire.input("col-md-2","Price",form.price,true) }}
                                {{ formulaire.input("col-md-2","",form.fix,false) }}
                            </div>
                            {{ macro.enregistrer }}
                        </form>
                    </div>
                    <div class="col-md-12">
                        <h5 class="over-title margin-bottom-15">Prices <span class="text-bold">list</span></h5>
                        <table class="table" id="sample-table-1">
                            <thead>
                                <tr>
                                    <th class="center">Room</th>
                                    <th class="center">Weeks</th>
                                    <th class="center">Price</th>
                                    <th class="center">State</th>
                                    <th class="center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for room in accommodation.rooms %}
                                    {% for price in room.prices %}
                                        <tr>
                                            {% if loop.index == 1 %}
                                                <td class="center" rowspan="{{ room.prices|length }}">{{ room }}</td>
                                            {% endif %}
                                            <td class="center">{{ price }}</td>
                                            <td class="center">{{ price.price }} {{ price.room.accommodation.schoolLocation.currency.code }} </td>
                                            <td class="center">{{ price.shoxFix }}</td>
                                            <td class="center">
                                                {{ macro.delete(path('delete_price',{'id':price.id})) }}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}